### ISSUE TITLE
Checking for updates phase!

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme-cli#19]
A quick check to find whether the current version of the package is up to date otherwise, showing a warning message and asking for an update.

Available utilities:
- [Johnnydep](https://pypi.org/project/johnnydep/)

There can be a quick yes/no question about whether the user wants to update the package.

**Comment by farhaduneci** [comment]
I would like to work on this one if you haven't already :crossed_fingers:

**Comment by lnxpy** [comment]
That's awesome. I checked some benchmarks and found that some packages are a bit slow in responding. Needs a bit of R&D.

**Comment by SepehrRasouli** [comment]
@lnxpy, Check [this](https://pypi.org/project/update-check/) out, I tried it and it works very well for pasteme.

**Comment by SepehrRasouli** [comment]
@lnxpy Can i be assigned ?

**Comment by SepehrRasouli** [comment]
Hi @lnxpy,  The library i told you about earlier checks if the two files **(either the python file itself by using the __file__ dunder method or a path to another file)** we give it as it's arguments are the same or not.
We can use this to our own advantage, for example:

1.  Check the `setup.py` file for the version number
2.  Create a constant called VERSION in the `constants.py` file and check that.

Which one do you think suits our needs the best ?

**Comment by lnxpy** [comment]
@SepehrRasouli We may not work on auto-update for now Sepehr. I have no plans for now.
