### ISSUE TITLE
Use `cowsay` or a better template for showing the "PASTE -->" message

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme-cli#2]

**Comment by SepehrRasouli** [comment]
Hi @lnxpy , May i work on this ?

**Comment by lnxpy** [comment]
Hi Sepehr. Of course you can. Let's see what you got. :)

**Comment by lnxpy** [comment]
@SepehrRasouli Talking of Cowsay, what do you think about the following pattern?

```
    /\  
   /  \ ~~> https://pasteme...
  /____\
```

Or something like a 3D small icon!

**Comment by SepehrRasouli** [comment]
> @SepehrRasouli Talking of Cowsay, what do you think about the following pattern?
> 
> ```
>     /\  
>    /  \ ~~> https://pasteme...
>   /____\
> ```
> 
> Or something like a 3D small icon!

@lnxpy I think this is very good, we can have a small dictionary of icons and randomly select from them. It's little bit more fancier, but i think it will improve the UX. What do you think ?

**Comment by lnxpy** [comment]
Well, think of two things!
- We should be thinking of responsiveness. Since we are showing only a URL, there is nothing serious that may break the responsiveness but the shapes!
- What kind of shapes? That would be so cool if we use small shapes of planets!

**Comment by SepehrRasouli** [comment]
Yes, I've researched about this and found [this](https://www.asciiart.eu/) website that has a lot of good ASCII arts, Small, Big, Large and about any subject! 
It even has some good [Planets ASCII Arts](https://www.asciiart.eu/space/planets). 
I think we can put these inside of a python file and randomly select one of them when printing out the logo. What do you think about it ? Is it an efficient way of solving this problem ?

**Comment by lnxpy** [comment]
It actually is but the thing is that they are not in the same category. So many diversities between shapes, sizes, styles, characters, and etc. We need to either find an ASCII pack or design them on our own.

**Comment by SepehrRasouli** [comment]
Yes, They're very different in shapes and sizes, but we can gather a list of those that we think are appropriate, randomly select one of them, and show it to the user.
Can i gather some, For an example ?

**Comment by SepehrRasouli** [comment]
> We need to either find an ASCII pack or design them on our own.

Dear @lnxpy, I've researched about designing our own ASCII logos, and I've found [ASCIflow](https://asciiflow.com/). If none of the ASCII arts in the website i gave didn't suit our needs, We can design them from here. 
What do you think ? Should we use this website to make our own logos ?

**Comment by lnxpy** [comment]
@SepehrRasouli Thanks you Sepehr jan. That would be so cool if we find some sort of a package or a collection that contains those ASCII shapes. At least, they are in the same style and scheme. Regardless of all, that's a bit tough designing them on our own!

**Comment by SepehrRasouli** [comment]
@lnxpy Any updates on the new PR ?
